/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 nb.gltf --transform
Author: Andrea Spognetta (Spogna) (https://sketchfab.com/spogna)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/used-new-balance-574-classic-free-f0aad4f64925479da3f607b186314eef
Title: Used New Balance 574 Classic   ▆ ▇ █ FREE █ ▇ ▆
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/nb-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh>
        <meshStandardMaterial color="purple" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/nb-transformed.glb");
